{
  "errorMessage": "list index out of range",
  "errorType": "IndexError",
  "requestId": "aed2e82a-8a74-4334-8cab-d5a0af6c2b98",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 1042, in lambda_handler\n    generate_csv_and_pdf_reports_for_the_drift_tables(reporting_db_secrets_client, reporting_db_secret_arn, table_names_list, scan_id)\n",
    "  File \"/var/task/lambda_function.py\", line 551, in generate_csv_and_pdf_reports_for_the_drift_tables\n    header_list = [str(i) for i in result[0]._asdict().keys()]\n"
  ]
}
