[ERROR] UnboundLocalError: local variable 'result_users' referenced before assignment
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 742, in lambda_handler
    for row in result_users:
